version: '3.8'

services:
  web:
    build: ./services/APIbot
    command: python main.py run -h 0.0.0.0
    volumes:
      - ./services/APIbot/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev